sudo: required

services:
  - docker

before-install:
  - docker build -t sagbiradar/docker-prod-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true sagbiradar/docker-prod-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: master
