version: "3"
services:
  docker-prod-react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    port:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "start", "test"]
